### ISSUE TITLE
Any plan on releasing the full dataset and data collection script?

### ISSUE THREAD

**Issue by AIasd** [yixiao1/Action-Based-Representation-Learning#2]
Hi!

I am just wondering when are you expecting to release the full dataset? 

Also, I wonder if you will release the script used to collect data?

Thank you so much!

**Comment by yixiao1** [comment]
Hi @AIasd,

Since the space needed for the full dataset is not yet ready, at present we are not ablt to public it.
Please refer to this [link](https://github.com/carla-simulator/data-collector) for CARLA data collection.

Cheers
