### ISSUE TITLE
$ACTIONDIR/carl/database/CoRL2020/small_dataset.json' and AttributeError: 'CEXP' object has no attribute '_client_vec' `

### ISSUE THREAD

**Issue by raozhongyu** [yixiao1/Action-Based-Representation-Learning#3]
Thanks for your great work, I meet this question`FileNotFoundError: [Errno 2] No such file or directory: '$ACTIONDIR/carl/database/CoRL2020/small_dataset.json' and AttributeError: 'CEXP' object has no attribute '_client_vec'
`
 I have checked there is the file in '$ACTIONDIR/carl/database/CoRL2020/small_dataset.json'  and i have set the `export ACTIONDIR=$(pwd)
`
Can you give me some suggestion, thanks a lot

**Comment by yixiao1** [comment]
Hi @raozhongyu,

Did you set your ACTIONDIR correctly with the directory? In order words, did you run `export ACTIONDIR=$(pwd)` under the downloaded repository directory?

**Comment by yixiao1** [comment]
There is no reply for a long time. This issue has been closed.
